version: '3.1'

volumes:
  prometheus-data:
  pmm-consul_data:
  pmm-mysql:
  pmm-grafana:

services:

### MariaDB ##############################################
  mariadb:
    build:
      context: ./mariadb
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    hostname: mariadb
    volumes:
      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
      - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    depends_on:
      - "pmm-server"
    command:
      - /bin/bash
      - -c
      - |
          /etc/init.d/mysqld start
          pmm-admin config --server pmm-server:80

### Percona ################################################
  percona:
    build:
      context: ./percona
    environment:
      - MYSQL_DATABASE=${PERCONA_DATABASE}
      - MYSQL_USER=${PERCONA_USER}
      - MYSQL_PASSWORD=${PERCONA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${PERCONA_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/percona:/var/lib/mysql
      - ${PERCONA_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${PERCONA_PORT}:3306"

### Adminer ###########################################
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"

### NetData ################################################
  netdata:
    image: titpetric/netdata:latest
    cap_add:
      - SYS_PTRACE
    volumes:
      - /:/host:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DOCKER_USR=root
    ports:
      - "${NETDATA_PORT}:19999"

### PMM Data ################################################
  pmm-data:   
    image: percona/pmm-server
    command: /bin/true
    volumes:
      - prometheus-data:/opt/prometheus/data
      - pmm-consul_data:/opt/consul-data
      - pmm-mysql:/var/lib/mysql
      - pmm-grafana:/var/lib/grafana

### PMM Server ################################################
  pmm-server:   
    image: percona/pmm-server
    volumes:
      - prometheus-data:/opt/prometheus/data
      - pmm-consul_data:/opt/consul-data
      - pmm-mysql:/var/lib/mysql
      - pmm-grafana:/var/lib/grafana
    ports:
      - "80:80"
    depends_on:
      - "pmm-data"