version: '3.1'

services:

  mariadb:
    image: mariadb
    restart: always
    volumes:
      - ./mariadb/config:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
    ports:
      - "${MARIADB_PORT}:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"