version: '3.1'

volumes:
  prometheus-data:
  pmm-consul_data:
  pmm-mysql:
  pmm-grafana:

services:

### MariaDB ##############################################
  mariadb:
    build:
      context: ./mariadb
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    hostname: mariadb
    volumes:
      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
      - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    depends_on:
      - "pmm-server"

### Percona ################################################
  percona:
    build:
      context: ./percona
    environment:
      - MYSQL_DATABASE=${PERCONA_DATABASE}
      - MYSQL_USER=${PERCONA_USER}
      - MYSQL_PASSWORD=${PERCONA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${PERCONA_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/percona:/var/lib/mysql
      - ${PERCONA_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${PERCONA_PORT}:3306"

### MySQL Backup ###########################################
  mysql-backup:
    image: camamber/mysql-backup-s3
    volumes:
      - ${DATA_PATH_HOST}/mysql/backup:/root/backup
    environment:
      - MYSQLDUMP_DATABASE=${MYSQLDUMP_DATABASE}
      - MYSQL_HOST=${MYSQLDUMP_HOST}
      - MYSQL_PORT=${MYSQLDUMP_PORT}
      - MYSQL_USER=${MYSQLDUMP_USER}
      - MYSQL_PASSWORD=${MYSQLDUMP_PASSWORD}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY_ID}
      - S3_SECRET_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET=${S3_BUCKET}
      - S3_PATH=${S3_PATH}
      - BACKUPS_TO_KEEP_LOCAL=${BACKUPS_TO_KEEP_LOCAL}
      - BACKUPS_TO_KEEP_S3=${BACKUPS_TO_KEEP_S3}

### Adminer ###########################################
  adminer:
    image: adminer:latest
    restart: always
    # ports:
    #   - "${ADMINER_PORT}:8080"

### NGINX Server #########################################
  nginx:
    build:
      context: ./nginx
      args:
        - CHANGE_SOURCE=${CHANGE_SOURCE}
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ${DATA_PATH_HOST}/nginx/.htpasswd:/var/www/.htpasswd
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - "netdata"
      - "adminer"

### NetData ################################################
  netdata:
    image: titpetric/netdata:latest
    cap_add:
      - SYS_PTRACE
    volumes:
      - /:/host:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DOCKER_USR=root
    # ports:
    #   - "${NETDATA_PORT}:19999"

### PMM Data ################################################
  pmm-data:   
    image: percona/pmm-server
    command: /bin/true
    volumes:
      - prometheus-data:/opt/prometheus/data
      - pmm-consul_data:/opt/consul-data
      - pmm-mysql:/var/lib/mysql
      - pmm-grafana:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini

### PMM Server ################################################
  pmm-server:   
    image: percona/pmm-server
    volumes:
      - prometheus-data:/opt/prometheus/data
      - pmm-consul_data:/opt/consul-data
      - pmm-mysql:/var/lib/mysql
      - pmm-grafana:/var/lib/grafana
      # - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "3000:80"
    depends_on:
      - "pmm-data"